api_settings:
  api_key: gAAAAABlJRze1yGLLwkNjITvYC-Mwal55VW37H0GLx8OePwSoKhB7xWnTK50rR7IaqtvfRYMCFwdjjk2NJgbajISmqP7TI4Kf0y33ZBkpI1BaVMNYBTblYNwP5EgsaRasIIVZuCBod4U16hXqn7J0arqtMqXXRzyLA==
character_details:
  class: barbarian
  level: '8'
  name: Dingus
  race: Tiefling
