api_settings:
  ai_model: gpt-3.5-turbo
  api_key: gAAAAABlJhCBgMSP3xv397tkDoP6VDLIAFmLYK5XtF-8q3zg8y3AgbsTgGS0pU8bAXmZ7ulKjg6pStQF-FzRGKdUnGZGnzxW819Ng1CNjT6ffW4WzHR-nFWMkJJywho_sVQXFasN2ErZbwUPoqkKmmR7tuEb_b7azA==
character_details:
  class: barbarian
  level: '8'
  name: Dingus
  race: Tiefling
