api_settings:
  api_key: gAAAAABlJcQ5F2kokbbIq9C_hiqBidwOd3SlfLp_mlPGTF_YLZAa4uEZffINbxtMD8bYcVJ6Ab3XG2L1ZyUeDwYZvYy9Txj_Yiztb5UzkwSd7rFlKrDcE_UcAyjZXxa7uuL8pLStZqXT8G_QNcpuswcdJh2OqjgI9A==
character_details:
  class: barbarian
  level: '8'
  name: Dingus
  race: Tiefling
